server:
  port: 9091

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/health_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 文件上传的前缀url
fileBaseUrl: http://localhost:9091

# 阿里云OSS配置
oss:
  # 注意：accessKeyId和accessKeySecret已从环境变量读取，不再从配置文件获取
  # 请设置环境变量 OSS_ACCESS_KEY_ID 和 OSS_ACCESS_KEY_SECRET
  
  # 其他OSS配置信息
  endpoint: oss-cn-shenzhen.aliyuncs.com  # OSS服务端点
  bucketName: healthsystem-bucket  # OSS存储桶名称
  fileUrl: https://healthsystem-bucket.oss-cn-shenzhen.aliyuncs.com  # OSS文件访问基础URL